### ISSUE TITLE
yum commands (and general doc clarification)

### ISSUE THREAD

**Issue by acquistomper** [doksu/selinux_policy_for_splunk#4]
First: you are awesome and I love you. I am running the policy on splunk hosts on rhel6 with only minor casualties. I feel if not safe, less naked.

Second: Perhaps your instructions are deliberately obtuse to discourage the ignorant. If not, kindly consider these clarifications:
# Packages

rhel6 has no "setools-devel" package that I could locate in the base or epel repos
- for my rhel6 hosts, /usr/share/selinux/devel/Makefile is provided by the package "selinux-policy"

----le snip---
# yum provides /usr/share/selinux/devel/Makefile

Loaded plugins: aliases, changelog, downloadonly, security, verify
selinux-policy-3.7.19-260.el6_6.5.noarch : SELinux policy configuration
Repo        : rhel-repo
Matched from:
Filename    : /usr/share/selinux/devel/Makefile

selinux-policy-3.7.19-260.el6_6.5.noarch : SELinux policy configuration
Repo        : installed
Matched from:
Other       : Provides-match: /usr/share/selinux/devel/Makefile

----el snip----
# Steps

I would suggest the clarifications below which take into account the item above>
- be root in a sensible directory
- yum install policycoreutils-python setools-console selinux-policy
- unzip selinux_policy_for_splunk-master.zip
- cd selinux_policy_for_splunk-master
- make -f /usr/share/selinux/devel/Makefile
- semodule -i splunk.pp
- semanage permissive -a splunk_t
- restorecon -R /opt/splunk
- restorecon /etc/init.d/splunk
- service splunk restart

**Comment by doksu** [comment]
Thanks very much for such generous feedback and yes you're right on all accounts. The instructions are deliberately written for a seasoned Linux sysadm who doesn't necessarily have SELinux experience, especially using custom policies. Not sure why I had 'setools-devel' in the package list - will remove now.

Nowadays, running an unconfined service seems downright dangerous, but most people don't realise the degree of protection provided by Type Enforcement. Have you used the Linux Auditd app's 'Type Enforcement' dashboard? (https://splunkbase.splunk.com/app/2642/) It automatically correlates AVCs with SYSCALL events to provide a really easy to read summary in the table at the bottom - it's saved me hours of manual work.

If you have any AVCs, be sure to send them my way so we can improve this policy.
